
% Parameter explanation:
% A(y) = A_s * (A_c + y * A_k) + (1 - A_s) * normpdf(y, A_mu, A_sigma)
% phi(y) = phi_s * (phi_c + y * phi_k) + (1 - phi_s) * normpdf(y, phi_mu, phi_sigma)

% {name, mutiplier, initial value, increment}
par_descs = {...
	{'nchan', 1, 30, 5},...
	{'dy', 1, 0.1, 0.01},...
	{'dt', 1e-3, 2, 1},...
	{'T', 1, 1, 1},...
	{'f', 1, 8, 1},...
    ...
	{'A_c', 1, 1, 0.1},...	
	{'A_k', 1, -0.3, 0.1},...
	{'A_mu', 1, 2, 0.1},...
	{'A_sigma', 1, 0.7, 0.1},...
	{'A_s', 1, 0, 0.1},...
    ...
    {'phi_c', 1, 0, 0.1},...	
	{'phi_k', 1, 1.5, 0.1},...
	{'phi_mu', 1, 0, 0.1},...
	{'phi_sigma', 1, 1, 0.1},...
	{'phi_s', 1, 1, 0.1},...
};

create_param_GUI(par_descs, @lfp_csd_proc_1, 3, 5,...
	'GUI_PARAMS',...
    1, 'lfp_csd_1');
